-- 도서관 마스터, 서지, 저작.
--
-- 설계 근거는 docs/구현계획.md 4절에 있습니다. 여기서는 그 가운데
-- 스키마만 보고는 알 수 없는 제약을 주석으로 남깁니다.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------
-- 도서관 마스터
-- ---------------------------------------------------------------

CREATE TABLE library (
    lib_code        varchar(20) PRIMARY KEY,
    short_id        smallint    NOT NULL UNIQUE,
    name            text        NOT NULL,
    name_norm       text        NOT NULL,
    lib_type        text,
    sido            text        NOT NULL,
    sigungu         text        NOT NULL,
    address_road    text,
    latitude        double precision,
    longitude       double precision,
    homepage_url    text,
    phone           text,
    closed_days     text,
    open_hours      jsonb,
    d4l_lib_code    text,
    std_match_score real,
    std_match_state text        NOT NULL DEFAULT 'unmatched'
                                CHECK (std_match_state IN ('auto', 'manual', 'unmatched')),
    holdings_mode   text        NOT NULL DEFAULT 'api'
                                CHECK (holdings_mode IN ('api', 'bulk')),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN library.lib_code IS
    '국립중앙도서관 도서관부호. 모든 소스를 잇는 공통 키입니다.';
COMMENT ON COLUMN library.short_id IS
    '소장 조회와 URL 인코딩에 쓰는 내부 번호. 한 번 발급하면 절대 바꾸거나 재사용하지 않습니다. '
    '선택 상태가 이 번호로 URL에 담기므로, 값이 바뀌면 공유된 링크가 전부 조용히 깨집니다.';
COMMENT ON COLUMN library.std_match_state IS
    '전국도서관표준데이터와의 대조 상태. 표준데이터에는 도서관부호가 없어 이름과 주소로 '
    '대조해야 하고, 실패하면 위경도가 없어 "내 주변" 경로에 나타나지 않습니다. '
    'manual 은 사람이 확인한 것이므로 재실행해도 덮어쓰지 않습니다.';
COMMENT ON COLUMN library.holdings_mode IS
    '소장 정보를 얻는 방식. 지금은 전부 api 입니다. 자주 가는 도서관을 미리 적재해 '
    '즉시 응답하게 만들고 싶어지면 그 도서관만 bulk 로 바꿉니다.';
COMMENT ON COLUMN library.lib_type IS
    '관종. 표준데이터에는 작은도서관과 대학·전문도서관이 섞여 있으므로 '
    '선택 화면에서는 공공도서관만 걸러야 목록이 쓸 만해집니다.';

CREATE INDEX library_region_idx ON library (sido, sigungu);
CREATE INDEX library_type_idx ON library (lib_type);
CREATE INDEX library_name_norm_idx ON library USING gin (name_norm gin_trgm_ops);

-- 위경도에는 공간 색인을 걸지 않습니다. 1,604행짜리 테이블에서 전체 훑기가
-- 색인 조회보다 빠르고, cube/earthdistance 확장 의존이 하나 줄어듭니다.

-- short_id 는 바뀌면 안 됩니다. 규칙을 문서로만 두면 언젠가 반드시 어겨지므로
-- DB에서 막습니다.
CREATE FUNCTION library_short_id_is_immutable() RETURNS trigger AS $$
BEGIN
    IF NEW.short_id IS DISTINCT FROM OLD.short_id THEN
        RAISE EXCEPTION
            'short_id 는 변경할 수 없습니다 (도서관부호 %, % -> %). '
            '이 번호는 공유된 URL 에 들어 있어 값이 바뀌면 링크가 전부 깨집니다.',
            OLD.lib_code, OLD.short_id, NEW.short_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER library_short_id_immutable
    BEFORE UPDATE ON library
    FOR EACH ROW EXECUTE FUNCTION library_short_id_is_immutable();

-- 소스마다 자기 도서관 ID 체계를 쓰므로 도서관부호와 잇는 표를 따로 둡니다.
CREATE TABLE library_source_link (
    source_code  text        NOT NULL,
    source_key   text        NOT NULL,
    lib_code     varchar(20) NOT NULL REFERENCES library ON DELETE CASCADE,
    match_method text        NOT NULL
                             CHECK (match_method IN ('exact_name', 'name_addr', 'geo', 'manual')),
    match_score  real,
    confirmed    boolean     NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (source_code, source_key)
);

COMMENT ON COLUMN library_source_link.confirmed IS
    '사람이 눈으로 확인한 연결. 대조를 다시 돌려도 이 행은 덮어쓰지 않습니다.';

CREATE INDEX library_source_link_lib_idx ON library_source_link (lib_code);

-- ---------------------------------------------------------------
-- 저작과 서지
-- ---------------------------------------------------------------

CREATE TABLE work (
    work_id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_key   text        NOT NULL,
    rep_book_id integer,
    is_manual   boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE work IS
    '사용자가 검색하는 단위. 판본과 표기가 달라도 같은 책이면 한 저작으로 묶입니다.';
COMMENT ON COLUMN work.work_id IS
    '공유 URL 에 들어가는 번호. 재군집화 때 최빈값으로 승계하고 절대 새로 매기지 않습니다. '
    '흡수된 번호는 bib_work_alias 에 남겨 301 로 넘깁니다.';
COMMENT ON COLUMN work.match_key IS
    '대표 정규화 키. 군집화는 그래프로 하므로 이 값이 유일하지는 않고, 사람이 들여다볼 때 씁니다.';
COMMENT ON COLUMN work.is_manual IS
    '사람이 손으로 구성을 고친 저작인지 여부.';

CREATE INDEX work_match_key_idx ON work (match_key);

CREATE TABLE book (
    book_id           integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn13            varchar(13) NOT NULL UNIQUE
                                  CHECK (isbn13 ~ '^97[89][0-9]{10}$'),
    isbn10            varchar(10),
    isbn_raw          text,
    set_isbn13        varchar(13),
    work_id           integer     REFERENCES work ON DELETE SET NULL,
    title             text        NOT NULL,
    subtitle          text,
    parallel_title    text,
    series_title      text,
    vol_no            smallint,
    edition_tokens    text[]      NOT NULL DEFAULT '{}',
    adaptation_tokens text[]      NOT NULL DEFAULT '{}',
    author_raw        text,
    publisher_raw     text,
    pub_date          date,
    price             integer,
    page_count        integer,
    kdc               text,
    keywords          text,
    title_key_core    text        NOT NULL,
    title_key_full    text        NOT NULL,
    alias_keys        text[]      NOT NULL DEFAULT '{}',
    author_norm       text,
    publisher_norm    text,
    source_code       text        NOT NULL,
    source_fetched_at timestamptz NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE book IS
    '도서관이 소장하는 단위. ISBN 하나가 한 행입니다.';
COMMENT ON COLUMN book.isbn_raw IS
    '정규화 이전의 원본. 부가기호가 섞여 들어온 값을 나중에 다시 볼 수 있게 남깁니다.';
COMMENT ON COLUMN book.adaptation_tokens IS
    '만화·청소년판·큰글자책 등. 병합 거부의 근거이므로 판본 표기와 절대 섞지 않습니다.';
COMMENT ON COLUMN book.edition_tokens IS
    '개정판·양장본 등. 같은 내용의 다른 인쇄이므로 묶되 화면 표시만 다르게 합니다.';
COMMENT ON COLUMN book.vol_no IS
    '권차. 표제 꼬리에서만 뽑습니다. 부표제의 숫자는 시리즈 번호일 때가 많아 권차로 삼으면 안 됩니다.';

CREATE INDEX book_work_idx ON book (work_id);
CREATE INDEX book_title_key_idx ON book (title_key_core);
CREATE INDEX book_alias_keys_idx ON book USING gin (alias_keys);
CREATE INDEX book_set_isbn_idx ON book (set_isbn13) WHERE set_isbn13 IS NOT NULL;

ALTER TABLE work
    ADD CONSTRAINT work_rep_book_fk FOREIGN KEY (rep_book_id)
        REFERENCES book ON DELETE SET NULL;

-- 세트 ISBN 은 낱권 저작에 직접 병합하지 않고 여기로만 잇습니다.
-- 병합해 버리면 "3권을 소장"과 "전집을 소장"이 구분되지 않습니다.
CREATE TABLE bib_set_member (
    set_isbn13    varchar(13) NOT NULL,
    member_isbn13 varchar(13) NOT NULL,
    seq           smallint,
    PRIMARY KEY (set_isbn13, member_isbn13)
);

CREATE INDEX bib_set_member_member_idx ON bib_set_member (member_isbn13);

-- ---------------------------------------------------------------
-- 군집화의 기록
-- ---------------------------------------------------------------

-- 흡수된 이전 work_id. GET /work/{id} 가 이 표를 거쳐 301 로 넘깁니다.
CREATE TABLE bib_work_alias (
    old_work_id integer     PRIMARY KEY,
    work_id     integer     NOT NULL REFERENCES work ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CHECK (old_work_id <> work_id)
);

CREATE INDEX bib_work_alias_target_idx ON bib_work_alias (work_id);

-- 판정 근거. 이것이 없으면 잘못된 묶음을 만났을 때 어느 규칙이 그랬는지 알 수 없습니다.
CREATE TABLE bib_merge_edge (
    a_isbn13   varchar(13) NOT NULL,
    b_isbn13   varchar(13) NOT NULL,
    rule_code  text        NOT NULL,
    confidence numeric(3,2) NOT NULL,
    verdict    text        NOT NULL CHECK (verdict IN ('MERGE', 'REVIEW')),
    run_id     bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (a_isbn13, b_isbn13),
    CHECK (a_isbn13 < b_isbn13)
);

COMMENT ON CONSTRAINT bib_merge_edge_check ON bib_merge_edge IS
    '쌍을 한 방향으로만 저장해 같은 관계가 두 행으로 갈라지지 않게 합니다.';

CREATE INDEX bib_merge_edge_review_idx ON bib_merge_edge (verdict, confidence)
    WHERE verdict = 'REVIEW';

-- 사람이 손으로 고친 판정. 자동 판정을 항상 이깁니다.
CREATE TABLE bib_merge_override (
    a_isbn13   varchar(13) NOT NULL,
    b_isbn13   varchar(13) NOT NULL,
    verdict    text        NOT NULL CHECK (verdict IN ('FORCE_MERGE', 'FORCE_SPLIT')),
    note       text,
    created_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (a_isbn13, b_isbn13),
    CHECK (a_isbn13 < b_isbn13)
);

COMMENT ON TABLE bib_merge_override IS
    '자동 판별은 반드시 틀립니다. 값싸게 고칠 수 있는 경로가 있어야 실제로 고치게 됩니다.';

-- 필드마다 어느 소스에서 왔는지. 소스를 추가해도 스키마를 바꾸지 않아도 되는 근거입니다.
CREATE TABLE bib_field_provenance (
    isbn13      varchar(13) NOT NULL,
    field_name  text        NOT NULL,
    source_code text        NOT NULL,
    value       text,
    trust       smallint    NOT NULL,
    observed_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (isbn13, field_name, source_code)
);

COMMENT ON TABLE bib_field_provenance IS
    '본 테이블의 값은 신뢰도가 가장 높은 비어 있지 않은 값입니다. '
    '예스24 같은 소스를 나중에 붙여도 서지정보 API 가 채운 필드를 덮어쓰지 않습니다.';

-- 저자 토큰의 말뭉치 빈도. 이 표가 있어야 한국어 저자명 대조가 성립합니다.
CREATE TABLE author_token_df (
    token      text        PRIMARY KEY,
    df_ratio   real        NOT NULL,
    doc_count  integer     NOT NULL,
    computed_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE author_token_df IS
    '롤링은 드물어 그것 하나로 동일인을 확정할 수 있고, 김은 흔해 아무것도 확정하지 못합니다. '
    '군집화를 돌릴 때마다 다시 만듭니다.';
