-- 소장 캐시와 운영 데이터.
--
-- 소장 관계를 미리 적재하지 않고 조회할 때 가져와 쌓는 설계입니다.
-- 근거는 docs/구현계획.md 3절과 8절에 있습니다.

-- ---------------------------------------------------------------
-- 소장 캐시
-- ---------------------------------------------------------------

CREATE TABLE holding_cache (
    isbn13      varchar(13) NOT NULL,
    region_code text        NOT NULL,
    lib_codes   text[]      NOT NULL,
    fetched_at  timestamptz NOT NULL DEFAULT now(),
    archive_key text,
    PRIMARY KEY (isbn13, region_code)
);

COMMENT ON TABLE holding_cache IS
    '버리는 데이터가 아니라 쌓이는 데이터입니다. 검색할 때마다 조회 결과가 누적되어 '
    '우리 소유의 소장 데이터가 되고, 쓸수록 빨라집니다.';
COMMENT ON COLUMN holding_cache.region_code IS
    '시도 코드. libSrchByBook 의 region 이 선택 항목이어서 전국을 한 번에 받으면 ALL 입니다.';
COMMENT ON COLUMN holding_cache.lib_codes IS
    'short_id 가 아니라 도서관부호로 저장합니다. 응답에 우리 마스터에 아직 없는 도서관이 '
    '나오더라도 값을 잃지 않고, 마스터를 갱신하면 그때부터 해석됩니다.';
COMMENT ON COLUMN holding_cache.fetched_at IS
    '만료시켜 버리지 않습니다. 오래된 항목도 이 시각과 함께 그대로 내보내고 배경에서 갱신합니다. '
    '화면에는 언제나 이 값을 표시해야 사용자가 "미소장"을 어떻게 읽을지 판단할 수 있습니다.';

-- 배경 갱신 대상을 고를 때 씁니다.
CREATE INDEX holding_cache_stale_idx ON holding_cache (fetched_at);
-- 특정 도서관이 나온 ISBN 을 찾을 때 씁니다. 링크 점검의 확인용 질의가 이걸 씁니다.
CREATE INDEX holding_cache_libs_idx ON holding_cache USING gin (lib_codes);

-- ---------------------------------------------------------------
-- 호출 예산
-- ---------------------------------------------------------------

CREATE TABLE api_budget (
    source_code text    NOT NULL,
    usage_date  date    NOT NULL,
    call_count  integer NOT NULL DEFAULT 0,
    PRIMARY KEY (source_code, usage_date)
);

COMMENT ON TABLE api_budget IS
    '일일 한도를 코드에서 지키는 원장. 재시작해도 유지되어야 하므로 DB 에 둡니다. '
    '한도의 80%% 에 도달하면 배경 갱신을 멈추고, 사람이 기다리는 요청을 우선합니다.';
COMMENT ON COLUMN api_budget.usage_date IS
    'Asia/Seoul 기준 날짜입니다. 저장은 UTC 로 하되 이 경계만은 한국 시각 개념입니다.';

-- ---------------------------------------------------------------
-- 적재 이력
-- ---------------------------------------------------------------

CREATE TABLE ingest_run (
    run_id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code   text        NOT NULL,
    scope_key     text,
    source_version text,
    mode          text        NOT NULL
                              CHECK (mode IN ('FULL_SNAPSHOT', 'INCREMENTAL', 'BACKFILL')),
    status        text        NOT NULL
                              CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'PARTIAL', 'SKIPPED')),
    started_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz,
    input_uri     text,
    input_sha256  text,
    rows_read     bigint,
    rows_ok       bigint,
    rows_rejected bigint,
    archive_key   text,
    error_class   text,
    error_message text
);

COMMENT ON COLUMN ingest_run.scope_key IS
    '재시도 가능한 최소 단위를 가리킵니다. 서지 백필이면 발행일 구간, 벌크면 도서관부호입니다.';

-- 같은 응답을 다시 적재하는 것이 자동으로 건너뛰기가 됩니다.
-- 파일이나 응답을 다시 받는 일은 반드시 생기므로 이 제약이 실질적인 안전장치입니다.
CREATE UNIQUE INDEX ingest_run_idempotency_idx
    ON ingest_run (source_code, coalesce(scope_key, ''), input_sha256)
    WHERE input_sha256 IS NOT NULL;

CREATE INDEX ingest_run_scope_idx ON ingest_run (source_code, scope_key, started_at DESC);
CREATE INDEX ingest_run_status_idx ON ingest_run (status) WHERE status <> 'SUCCEEDED';

-- 변환할 수 없는 레코드는 예외를 던지지 않고 여기에 건수로 남깁니다.
-- 한 줄의 형식이 이상하다고 그 구간 전체의 적재가 중단되면 안 됩니다.
CREATE TABLE ingest_reject (
    run_id      bigint      NOT NULL REFERENCES ingest_run ON DELETE CASCADE,
    line_no     integer,
    raw_line    text,
    reason_code text        NOT NULL,
    detail      text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ingest_reject_run_idx ON ingest_reject (run_id);

-- ---------------------------------------------------------------
-- 리다이렉트 템플릿과 링크 점검
-- ---------------------------------------------------------------

CREATE TABLE opac_template (
    family_code       text    PRIMARY KEY,
    url_pattern       text    NOT NULL,
    query_kind        text    NOT NULL
                              CHECK (query_kind IN ('ISBN', 'TITLE', 'TITLE_AUTHOR')),
    encoding          text    NOT NULL DEFAULT 'UTF-8',
    no_result_markers text[]  NOT NULL DEFAULT '{}',
    ok_markers        text[]  NOT NULL DEFAULT '{}',
    notes             text
);

COMMENT ON COLUMN opac_template.encoding IS
    '국내 OPAC 중에는 한글 질의를 EUC-KR 로 퍼센트 인코딩해야 하는 곳이 아직 있습니다. '
    'UTF-8 로 보내면 HTTP 200 이 오면서 결과만 0건이 되는데, 조용히 실패하는 가장 나쁜 형태입니다.';
COMMENT ON COLUMN opac_template.no_result_markers IS
    '국내 OPAC 은 결과가 없어도 대부분 200 을 반환합니다. 상태 코드만 보는 점검은 '
    '아무것도 검증하지 못하므로 본문에서 이 문구를 찾습니다.';

CREATE TABLE library_opac (
    lib_code             varchar(20) PRIMARY KEY REFERENCES library ON DELETE CASCADE,
    family_code          text        REFERENCES opac_template,
    base_url             text        NOT NULL,
    vars                 jsonb       NOT NULL DEFAULT '{}',
    detail_url_pattern   text,
    fallback_url         text        NOT NULL,
    status               text        NOT NULL DEFAULT 'UNKNOWN'
                                     CHECK (status IN ('UNKNOWN', 'OK', 'BROKEN', 'BLOCKED', 'UNVERIFIABLE')),
    last_checked_at      timestamptz,
    consecutive_failures smallint    NOT NULL DEFAULT 0
);

COMMENT ON COLUMN library_opac.fallback_url IS
    '반드시 채웁니다. 표준데이터의 홈페이지주소가 있으므로 링크가 없어 아무 데도 못 가는 '
    '경우는 발생하지 않습니다. 다만 어느 단계의 링크인지 화면에 정직하게 표시해야 합니다.';
COMMENT ON COLUMN library_opac.status IS
    'UNVERIFIABLE 은 자바스크립트로만 동작하거나 POST 만 받는 OPAC 입니다. '
    '헤드리스 브라우저를 만들지 않고 링크는 살려 둔 채 사용자 신고를 받습니다.';

CREATE TABLE link_check (
    check_id    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lib_code    varchar(20) NOT NULL REFERENCES library ON DELETE CASCADE,
    checked_at  timestamptz NOT NULL DEFAULT now(),
    probe_kind  text        NOT NULL CHECK (probe_kind IN ('HEAD_BASE', 'GET_SEARCH_CANARY')),
    http_status integer,
    latency_ms  integer,
    final_url   text,
    result      text        NOT NULL,
    detail      text
);

CREATE INDEX link_check_lib_idx ON link_check (lib_code, checked_at DESC);

-- 어느 템플릿이 실제로 쓰이는지 알아야 점검 대상을 좁힐 수 있습니다.
CREATE TABLE click_log (
    lib_code   varchar(20) NOT NULL REFERENCES library ON DELETE CASCADE,
    work_id    integer,
    template_kind text,
    clicked_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX click_log_recent_idx ON click_log (clicked_at DESC);
CREATE INDEX click_log_lib_idx ON click_log (lib_code, clicked_at DESC);

-- ---------------------------------------------------------------
-- 검색 사전
-- ---------------------------------------------------------------

CREATE TABLE search_synonym (
    term      text NOT NULL,
    canonical text NOT NULL,
    kind      text NOT NULL CHECK (kind IN ('title', 'author', 'publisher')),
    PRIMARY KEY (term, kind)
);

COMMENT ON TABLE search_synonym IS
    '자동 추출은 오탐이 늘고 검증이 어렵습니다. 실제로 검색에 실패한 사례를 보고 '
    '손으로 추가하는 편이 이 규모에서는 낫습니다.';
